server:
  port: 8080

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
  h2:
    console:
      enabled: true

java:
  runtime:
    version: 11
#spring:
#  datasource:
#    url: jdbc:mysql://us-cdbr-east-02.cleardb.com/heroku_f5f811d913212b0?reconnect=true:3306/
#    username: b1055f53485500
#    password: 1e63fd13
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database: mysql

    generate-ddl: true
    hibernate:
      ddl-auto: create